### ISSUE TITLE
Programming in Java Nptel Program description Issue

### ISSUE THREAD

**Issue by bshubham5359** [bkkothari2255/Programming_In_Java_NPTEL#1]

**Comment by bkkothari2255** [comment]
@bshubham5359 Code description is not required. If you have any question then you can ask or refer NPTEL lectures or Prof. Debasis Samantha website at [Object Oriented Programming with Java
by Debasis Samanta](https://cse.iitkgp.ac.in/~dsamanta/java/index.htm).

**Comment by jetaimejanu** [comment]
Sir Can u send the solutions for Assignment Quiz not programs for Programing in java nptel 2020
