### ISSUE TITLE
Non-proctored Exam

### ISSUE THREAD

**Issue by vbvasare** [bkkothari2255/Programming_In_Java_NPTEL#2]
sir can you please provide the non proctered exam file to get an idea of non proctered online exam

**Comment by bkkothari2255** [comment]
Refer to this article 
[Proctored Exam Meaning](https://www.onlineexambuilder.com/knowledge-center/exam-knowledge-center/proctored-exam-meaning/item12515)

Quora
[How do I prepare for the NPTEL exam?](https://www.quora.com/How-do-I-prepare-for-the-NPTEL-exam?ch=10&share=40628425&srid=uz1U0)
